import Head from 'next/head'
import Navbar from "../components/navbar";
import Featured from "../components/featured";
import List from "../components/list";

export default function Home() {
  return (
    <div className="home">
      <Head>
        <title>StachowiApps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div className="">
              <Navbar />
              <Featured />
              <List title="Skills"/>
              <List title="Experiences"/>
              <List title="Projects"/>
              <List title="Awards/Certifications"/>
          </div>
      </main>
    </div>
  )
}
